// Generated by the Magnus repo: terminal-theme/tools/build-web.mjs. Do not edit by hand.
export const PALETTES = [
  {
    "key": "life-tracker",
    "label": "Life Tracker"
  },
  {
    "key": "heather",
    "label": "Heather"
  },
  {
    "key": "lakeglow",
    "label": "Lakeglow"
  },
  {
    "key": "beacon",
    "label": "Beacon"
  }
];
export const DEFAULT_PALETTE = 'life-tracker';
