// Runs in <head>, before the page is drawn, so there's no flash of the wrong
// theme. (A plain script file, since the Content-Security-Policy doesn't
// allow inline scripts.)
//
// Two independent choices, both saved per device in localStorage:
//   palette  – which color theme (themes.css), e.g. "heather"
//   mode     – "auto" (follow the system light/dark setting), "light", "dark"
// The palette list itself lives in js/palettes.js (generated by Magnus).
(function () {
  var PALETTE_KEY = 'kanban.palette';
  var MODE_KEY = 'kanban.themeMode';
  var root = document.documentElement;
  var media = window.matchMedia ? window.matchMedia('(prefers-color-scheme: dark)') : null;

  function read(key, fallback) {
    try {
      return localStorage.getItem(key) || fallback;
    } catch (e) {
      return fallback;
    }
  }
  // The "life-tracker" theme was renamed "hearth"; carry saved choices over.
  if (read(PALETTE_KEY, '') === 'life-tracker') {
    try {
      localStorage.setItem(PALETTE_KEY, 'hearth');
    } catch (e) {}
  }
  function write(key, value) {
    try {
      localStorage.setItem(key, value);
    } catch (e) {}
  }

  function apply() {
    var mode = read(MODE_KEY, 'auto');
    var dark = mode === 'dark' || (mode === 'auto' && !!media && media.matches);
    root.setAttribute('data-palette', read(PALETTE_KEY, 'hearth'));
    if (dark) root.setAttribute('data-theme', 'dark');
    else root.removeAttribute('data-theme');
    // Browser/phone chrome color follows the theme background.
    var meta = document.querySelector('meta[name="theme-color"]');
    var bg = getComputedStyle(root).getPropertyValue('--theme-color').trim();
    if (meta && bg) meta.setAttribute('content', bg);
    // App icon follows the theme (icons/ is generated by scripts/generate-icon.py).
    // The tab icon updates live; iOS only reads the touch icon when you
    // "Add to Home Screen", so the home-screen icon keeps the theme it had then.
    var palette = root.getAttribute('data-palette');
    var icon = document.querySelector('link[rel="icon"]');
    var touch = document.querySelector('link[rel="apple-touch-icon"]');
    if (icon) icon.setAttribute('href', 'icons/' + palette + '-favicon.png');
    if (touch) touch.setAttribute('href', 'icons/' + palette + '-180.png');
  }

  if (media && media.addEventListener) {
    media.addEventListener('change', function () {
      if (read(MODE_KEY, 'auto') === 'auto') apply();
    });
  }

  window.lifeTrackerTheme = {
    apply: apply,
    getPalette: function () {
      return read(PALETTE_KEY, 'hearth');
    },
    setPalette: function (key) {
      write(PALETTE_KEY, key);
      apply();
    },
    getMode: function () {
      return read(MODE_KEY, 'auto');
    },
    setMode: function (mode) {
      write(MODE_KEY, mode);
      apply();
    },
  };

  apply();
})();
